name: todo-manager

services:
  db:
    image: postgres:latest
    container_name: ${DB__NAME}
    restart: always
    ports:
      - "${DB__PORT}:5432"
    environment:
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  #   restart: always
  #   volumes:
  #     - ./api:/app
  #   ports:
  #     - "8000:8000"
  #   working_dir: /app
  #   command: uv run main:app --host 0.0.0.0 --reload

  nginx:
    container_name: nginx_proxy
    ports:
      - "5000:80"
    restart: always
    build:
      dockerfile_inline: |
        FROM nginx:latest
        COPY ./nginx.dev.conf /etc/nginx/conf.d/default.conf
      context: .
    develop:
      watch:
        - action: sync+restart
          path: ./nginx.dev.conf
          target: /etc/nginx/conf.d/default.conf

volumes:
  db_data:

