// This file is auto-generated by @hey-api/openapi-ts

import type {
  GetTodosResponse,
  CreateTodoResponse,
  GetTodoByIdResponse,
  UpdateTodoResponse,
} from "./types.gen";

const todoSchemaSchemaResponseTransformer = (data: any) => {
  if (data.dueDate) {
    data.dueDate = new Date(data.dueDate);
  }
  return data;
};

export const getTodosResponseTransformer = async (
  data: any,
): Promise<GetTodosResponse> => {
  data = data.map((item: any) => {
    return todoSchemaSchemaResponseTransformer(item);
  });
  return data;
};

export const createTodoResponseTransformer = async (
  data: any,
): Promise<CreateTodoResponse> => {
  data = todoSchemaSchemaResponseTransformer(data);
  return data;
};

export const getTodoByIdResponseTransformer = async (
  data: any,
): Promise<GetTodoByIdResponse> => {
  data = todoSchemaSchemaResponseTransformer(data);
  return data;
};

export const updateTodoResponseTransformer = async (
  data: any,
): Promise<UpdateTodoResponse> => {
  data = todoSchemaSchemaResponseTransformer(data);
  return data;
};
