// This file is auto-generated by @hey-api/openapi-ts

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * TodoCreateSchema
 */
export type TodoCreateSchema = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description: string;
  /**
   * Iscompleted
   */
  isCompleted?: boolean | null;
  /**
   * Duedate
   */
  dueDate: Date | null;
};

/**
 * TodoSchema
 */
export type TodoSchema = {
  /**
   * Title
   */
  title: string;
  /**
   * Description
   */
  description: string;
  /**
   * Iscompleted
   */
  isCompleted: boolean;
  /**
   * Duedate
   */
  dueDate: Date | null;
  /**
   * Id
   */
  id: number;
};

/**
 * TodoUpdateSchema
 */
export type TodoUpdateSchema = {
  /**
   * Title
   */
  title?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Is Completed
   */
  is_completed?: boolean | null;
  /**
   * Due Date
   */
  due_date?: Date | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type HealthData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/health";
};

export type HealthResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetTodosData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/todos";
};

export type GetTodosResponses = {
  /**
   * Response Get Todos Api Todos Get
   * Successful Response
   */
  200: Array<TodoSchema>;
};

export type GetTodosResponse = GetTodosResponses[keyof GetTodosResponses];

export type CreateTodoData = {
  body: TodoCreateSchema;
  path?: never;
  query?: never;
  url: "/api/todos";
};

export type CreateTodoErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateTodoError = CreateTodoErrors[keyof CreateTodoErrors];

export type CreateTodoResponses = {
  /**
   * Successful Response
   */
  201: TodoSchema;
};

export type CreateTodoResponse = CreateTodoResponses[keyof CreateTodoResponses];

export type DeleteTodoData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/api/todos/{id}";
};

export type DeleteTodoErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteTodoError = DeleteTodoErrors[keyof DeleteTodoErrors];

export type DeleteTodoResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteTodoResponse = DeleteTodoResponses[keyof DeleteTodoResponses];

export type GetTodoByIdData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/api/todos/{id}";
};

export type GetTodoByIdErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTodoByIdError = GetTodoByIdErrors[keyof GetTodoByIdErrors];

export type GetTodoByIdResponses = {
  /**
   * Successful Response
   */
  200: TodoSchema;
};

export type GetTodoByIdResponse =
  GetTodoByIdResponses[keyof GetTodoByIdResponses];

export type UpdateTodoData = {
  body: TodoUpdateSchema;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/api/todos/{id}";
};

export type UpdateTodoErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateTodoError = UpdateTodoErrors[keyof UpdateTodoErrors];

export type UpdateTodoResponses = {
  /**
   * Successful Response
   */
  200: TodoSchema;
};

export type UpdateTodoResponse = UpdateTodoResponses[keyof UpdateTodoResponses];

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};
